[project]
name = "librarysite"
version = "0.1.2"
dependencies = [
    "Django==6.0.5",
    "django-jazzmin==3.0.1",
    "psycopg2-binary==2.9.12",
    "dj-database-url==3.1.2",
    "asgiref==3.11.1",
    "sqlparse==0.5.5",
    "tzdata==2026.2"
]

[tool.vercel]
entrypoint = "librarysite.wsgi:application"

[tool.vercel.scripts]
build = "python manage.py makemigrations --merge --noinput && python manage.py migrate && python manage.py collectstatic --noinput"