# Generated by Django 6.0.5 on 2026-05-25 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('total_number_of_pages', models.IntegerField(default=100)),
                ('available', models.BooleanField(default=True)),
                ('deposit_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('borrow_fee', models.IntegerField(default=10)),
                ('payment_number', models.CharField(default='9833950030', max_length=50)),
                ('call_number', models.CharField(blank=True, help_text='e.g., PR 6056 .I2 Z5 2026', max_length=100, null=True)),
            ],
            options={
                'ordering': ['call_number', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(blank=True, max_length=100, null=True)),
                ('borrower_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved / Out for Delivery'), ('RETURNED', 'Returned / Closed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('delivery_location', models.CharField(default='Self Pick-up from Library', max_length=255)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to='books.book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
