# Generated by Django 6.0.5 on 2026-05-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='delivery_location',
            field=models.CharField(default='Main Library Pick-up', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='payment_number',
            field=models.CharField(default=9833770438, max_length=50),
        ),
    ]
