# Generated by Django 6.0.5 on 2026-05-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_isbn_book_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='totalnumberofpages',
            new_name='total_number_of_pages',
        ),
    ]
