# Generated by Django 6.0.5 on 2026-05-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_borrowrequest_borrower_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='borrow_fee',
        ),
        migrations.AddField(
            model_name='book',
            name='borrow_fee_percentage',
            field=models.IntegerField(default=10, help_text='Enter fee as a percentage of the deposit'),
        ),
    ]
