# Generated by Django 6.0.5 on 2026-05-25 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_borrow_fee_book_borrow_fee_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['call_number', 'title']},
        ),
        migrations.RenameField(
            model_name='borrowrequest',
            old_name='request_date',
            new_name='requested_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='borrow_fee_percentage',
        ),
        migrations.RemoveField(
            model_name='book',
            name='location',
        ),
        migrations.AddField(
            model_name='book',
            name='borrow_fee',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='book',
            name='call_number',
            field=models.CharField(blank=True, help_text='e.g., PR 6056 .I2 Z5 2026', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='deposit_fee',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='book',
            name='payment_number',
            field=models.CharField(default='9833950030', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_number_of_pages',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='delivery_location',
            field=models.CharField(default='Self Pick-up from Library', max_length=255),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved / Out for Delivery'), ('RETURNED', 'Returned / Closed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
