# Generated by Django 6.0.5 on 2026-05-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_totalnumberofpages_book_total_number_of_pages'),
        ('books', '0004_create_prod_admin'),
    ]

    operations = [
    ]
